### ISSUE TITLE
(Suggestion) affiche tous les livres quand barre de recherche vide

### ISSUE THREAD

**Issue by FLorianBlm** [WildCodeSchool/tours-php-2009-project2-mybooks#30]
Actuellement quand on clique sur la loupe de recherche quand la barre est vide, ça nous affiche qu’un seul livre.
Peut-être qu'il pourrait afficher toute la liste de livre.

**Comment by rickifox** [comment]
Quand une recherche n'a rien à afficher il nous semble logique de ne rien afficher ^^'
