### ISSUE TITLE
I read a book in the future

### ISSUE THREAD

**Issue by leobro7** [WildCodeSchool/tours-php-2009-project2-mybooks#35]
I can choose a future date

**Comment by AurelieFqt** [comment]
Tu es sur quel navigateur ? @leobro7

**Comment by axelhamil** [comment]
On safari the date type of the forms doesn't support

**Comment by leobro7** [comment]
j'ai essayé sur chrome et safari, j'ai le même résultat: Ajouter un livre comme "lu" à une date future

**Comment by axelhamil** [comment]
**Weird, when I try to enter a future date, I do have a message forbidding me to put a date greater than today's date.**

<img width="1160" alt="Capture d’écran 2020-11-25 à 16 09 09" src="https://user-images.githubusercontent.com/68954111/100247005-2462de80-2f3a-11eb-84a2-a3ade8276599.png">

**Comment by leobro7** [comment]
ah mince pas chez moi
